export const langs = [
  { id: "c", title: "C" },
  { id: "cpp", title: "C++" },
  { id: "csharp", title: "C#" },
  { id: "shell", title: "Shell" },
  { id: "ruby", title: "Ruby" },
  { id: "haskell", title: "Haskell" },
  { id: "python", title: "Python" },
  { id: "go", title: "Go" },
  { id: "java", title: "Java" },
  { id: "javascript", title: "JavaScript" },
  { id: "php", title: "PHP" },
  { id: "perl", title: "Perl" },
  { id: "brainfuck", title: "Brainfuck" },
  { id: "nadesiko3", title: "Nadesiko3" },
  { id: "wenyan", title: "Wenyan" },
];
